### ISSUE TITLE
phantom 1.9.10 - queries problems and consistency level   

### ISSUE THREAD

**Issue by Kenzo777** [websudos/phantom#287]
1. Using where clause with "AND" not working 
2. Set consistency level on any query not working 

1.8.12 works fine with "Where" and "AND" but not with Consistency level 

XXXTable
  .select
  .where(_.id eqs someId)
  .and(_.timeUUID lt from.getOrElse(UUIDs.timeBased()))
  .limit(pageSize)
  .fetch()

**Comment by alexflav23** [comment]
Hi @Kenzo777 , I doubt the `and` part is not working on the basis of tests passing and no other reports being made, but if you could please create a gist or paste a complete example here I will check it out. We have extensive tests for `and`. Consistency levels have been somewhat of a problem as they have completely changed in newer versions of CQL and there is really no great way to set them on a per query level anymore.

You have to run 2 queries now essentially:

```scala

USE CONSISTENCY QUORUM;

UPDATE TABLE WHERE blabla;
```

**Comment by Kenzo777** [comment]
"And" operation part not working also At the new 1.10.1 it's working in 1.8.12 .   
All tests not including any - select where query with "and" operation - 

CREATE TABLE IF NOT EXISTS timeline(
	tag		text,
	timeIndex timeuuid,
	data         text, 
	PRIMARY KEY(tag,timeIndex)
)
WITH CLUSTERING ORDER BY (timeIndex DESC)

if we want to query this table with phantom dsl .

TimelineTable.select
      .where(_.tag eqs "SOME_TAG")
      .and(_.timeIndex lt UUIDs.timeBased())
      .limit(pageSize)
      .fetch()


same example works fine in 1.8.12  . but the newer version return error message :  java.lang.NoSuchMethodError: com.websudos.phantom.builder.query.Query.and(Lscala/Function1;)Lcom/websudos/phantom/builder/query/Query;

**Comment by alexflav23** [comment]
Hi @Kenzo777 ,

I think you have a dependency conflict with phantom in your classpath, but unless you post the full stacktrace properly I cannot help you. Consistency level of a per level basis has been removed in Cassandra, not in phantom so it will not work anymore, you have to set it at protocol level instead.

Please post the full stacktrace, I am fairly confident you are experiencing a dependency collision problem and that phantom does work as expected there otherwise no one would use it.

Regards,
Flavian
