### ISSUE TITLE
1.8 cannot update secondary indexed column

### ISSUE THREAD

**Issue by brianwawok** [websudos/phantom#232]
Not sure if this is good or bad to do, but it definitely worked in 1.5.

```
package foo

import foo.data.DBConnector
import com.websudos.phantom.dsl._

import scala.concurrent.Future


case class TestUpdate(key1: String, key2: String)


sealed class TestUpdater extends CassandraTable[TestUpdater, TestUpdate] with DBConnector {

  object key1 extends StringColumn(this) with PartitionKey[String]

  object key2 extends StringColumn(this) with Index[String]

  override def fromRow(row: Row): TestUpdate = {
    TestUpdate(
      key1(row),
      key2(row)
    )
  }
}

object TestUpdater extends TestUpdater {

  def update(tu: TestUpdate): Future[ResultSet] = {

    TestUpdater
    .update()
      .where(_.key1 eqs tu.key1)
      .modify(_.key2 setTo tu.key2)
      .future()
  }

}
```

This now is a compile time error like:

```
Error:(33, 22) Play 2 Compiler: 
 C:\code\\TestUpdater.scala:33: value setTo is not a member of object x$2.key2
       .modify(_.key2 setTo tu.key2)
                      ^
```

if I removed index from the table def it works.. or if I use 1.5.

**Comment by alexflav23** [comment]
@brianwawok Thank you for reporting this. As far as I am aware, Cassandra doesn't allow updating of Indexes and it's why we've inserted a compile time error as you describe.

**Comment by brianwawok** [comment]
@alexflav23 it totally works fine on SECONDARY indexes.  You cannot change primary key..


see demo:

```

CREATE TABLE foobar (
  key1 varchar PRIMARY KEY,
  key2 varchar
);

CREATE INDEX foobar_key2 ON foobar (key2);

insert into foobar(key1, key2) values ('a', 'b');

update foobar set key2 = 'c' where key1 = 'a';

select * from foobar ;


 key1 | key2
------+------
    a |    c
```

**Comment by alexflav23** [comment]
@brianwawok I've added a ticket for this internally and it should be resolved fairly quickly. I will keep you up-to-date with progress.

**Comment by brianwawok** [comment]
@alexflav23 cool, I can pull a snapshot when it is available and test...  I have a fairly big app, so we will see if I catch any other glitches in the upgrade.

**Comment by alexflav23** [comment]
@brianwawok A 1.8.3 will be released later today to sort this issue out. I will update you once it's live.

**Comment by brianwawok** [comment]
@alexflav23 great I will let you know how it works!

**Comment by alexflav23** [comment]
@brianwawok 1.8.4 is now on its way to Maven Central and it should be live within an hour or two. 1.8.3 was published to bintray which keeps rate limiting us to 5 rest api calls a day in hope of petty dollar.

**Comment by alexflav23** [comment]
@brianwawok 1.8.4 is live and this issue has been resolved. I will now close this ticket. Let us know if you experience any further problems.

**Comment by brianwawok** [comment]
@alexflav23 bintray comment extra funny because I worked for Sonatype until 2 weeks ago ;)

**Comment by kareblak** [comment]
I am still experiencing the problem 1.8.4. I have a table consisting of a composite key containing with two fields, and a third which I've tried to secondary index, but `setTo` is still not a member of the field. Also, should a field with clustering order be mutable? This doesn't work either.

**Comment by alexflav23** [comment]
@kareblak Cluster order fields are part of the primary, they are certainly not mutable. Strangely enough I have added tests for secondary keys, so maybe try adding ```import com.websudos.phantom.dsl._``` at the top of your file, you should get the implicit conversion for that ```setTo``` method.

**Comment by kareblak** [comment]
Yes, I realized that the question was rather silly. `dsl._` is being imported, but it doesn't seem to make a difference. I'll look into it.

**Comment by alexflav23** [comment]
@kareblak Have a look at the tests (here)[https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/db/specialized/SecondaryIndexTest.scala], perhaps those will point you in the right direction.

**Comment by brianwawok** [comment]
@alexflav23 it is rather hard to consume to see how 1.8.4 works, because the publish to maven central is missing pom.xml, and http://maven.websudos.co.uk/ext-releases-local appears to be down....  also makes it impossible to build the github repo locally

**Comment by kareblak** [comment]
Yes, I think my issue was due to the wrong dependencies being pulled in when i manually uploaded the 1.8.4 jar to my repo. @brianwawok this has already been reported in #240

**Comment by alexflav23** [comment]
@brianwawok We have moved all our releases to Bintray, which is still causing some issues. Phantom should be available to download from bintray alongside all dependencies, including finagle-zookeeper.

**Comment by brianwawok** [comment]
@alexflav23 the Bintray situation is not much improved. I DO see 2.10 version of 1.8.4 in bintray, but it appears that the 2.11 cross-compile is missing.

**Comment by foovungle** [comment]
What's the new Bintray resolver string for sbt? thx

**Comment by brianwawok** [comment]
@foovungle   https://dl.bintray.com/websudos/oss-releases/
